// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nuclear-destroy/NuclearDestroy.tsx": () => import("../components/mockups/nuclear-destroy/NuclearDestroy.tsx")
};
